### ISSUE TITLE
Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead

### ISSUE THREAD

**Issue by LunicLynx** [soxtoby/SlackNet#22] opened 2019-10-28 14:54 UTC
First of all this project is awesome and should be the default recommendation for slack.

Here the issue though:

`Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead.`

I need to add the following code in startup: 

```csharp
services.Configure<IISServerOptions>(options =>
{
    options.AllowSynchronousIO = true;
});
```

I expect you are using synchronous calls somewhere.

**Comment by mrmurb** [comment] 2019-10-31 10:33
This is caused by targeting a .Net Core 3.0 project. [ref](https://github.com/graphql-dotnet/graphql-dotnet/issues/1326)

Fixing this would mean migrating from `Newtonsoft.Json` to the native `System.Text.Json` lib.

**Comment by soxtoby** [comment] 2019-11-05 11:21
Should be fixed now - I think there was only the one place that was reading from the request body synchronously.

**Comment by soxtoby** [comment] 2019-11-05 11:21
``

**Closed by soxtoby** 2019-11-05 11:21 UTC
Labels: bug
